# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b942a277aa6bdfd7cbf5d2bd0f71beaec34db21d724d02f0c361583108a15b7f07834fc1de25effc45878d034247f5458c0ae79fc458f4e4439713198794661

test:
  secret_key_base: 1ea824519d0cd86893e8731d7d5808141ce85abeb123ca88deb553c9fb616ff36059d691cd436955492235ce6ebe1ef4480bfb144741d8ea68c9dd19e3cf146c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
